/**
 * pi adapter for the hard-gate policy.
 *
 * pi's extension API offers two points this gate needs:
 *   pi.on('tool_call', ...) -> { block: true, reason }   (enforce)
 *   pi.on('context',   ...) -> { messages }              (remind each turn)
 *
 * Everything that decides *whether* to block lives in ../policy.js. This file
 * only translates: pi event -> normalized input -> policy question -> pi result.
 *
 * Install: copy this directory to <pi agent dir>/extensions/enforce-rules/
 * Installed by the bridge itself: bridge/lib/gates.js plans these files, so `adopt`
 * snapshots them and `revoke` removes them again.
 */

import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  loadPolicy,
  newSessionState,
  normalizePath,
  policyFromObject,
  recordSignal,
  recordWrite,
  reminderFor,
  shouldBlock,
} from '../policy.js';

const HERE = dirname(fileURLToPath(import.meta.url));

/**
 * The filesystem probe the policy consults.
 *
 * Everything here answers instead of throwing: a probe that throws turns a
 * filesystem hiccup into a dead gate, and a gate that stops existing is the one
 * failure this design is built to avoid. `listDir` and `statMtime` exist for
 * the index-freshness rule; the plain `exists` is what scoping uses.
 */
export const realFs = {
  exists: (p) => existsSync(p),
  statMtime: (p) => {
    try {
      return statSync(p).mtimeMs;
    } catch {
      return 0;
    }
  },
  listDir: (dir) => {
    try {
      return readdirSync(dir);
    } catch {
      return [];
    }
  },
};

/**
 * Where the policy JSON can live.
 *
 * Two layouts have to work, and getting this wrong fails SILENTLY (the gate
 * falls back to fail-open), which is the worst possible failure mode for an
 * enforcement point:
 *
 *   repo checkout : bridge/gates/pi/policy.json      <- next to this adapter
 *   installed     : <gate dir>/pi/index.js
 *                   <gate dir>/policy.json          <- generated by the installer
 *
 * So the adapter-local file is checked first (developer layout), then the gate
 * root (installed layout). A caller-supplied path always wins.
 */
export const policyCandidates = (here, explicit) =>
  [explicit, join(here, 'policy.json'), join(here, '..', 'policy.json')].filter(Boolean);

export const firstExistingPolicy = (here, explicit, exists = existsSync) => {
  for (const candidate of policyCandidates(here, explicit)) {
    if (exists(candidate)) return candidate;
  }
  return null;
};

/** Tool names that count as "the model consulted the code graph". */
const SIGNAL_TOOLS = [
  'search_graph',
  'trace_path',
  'get_code_snippet',
  'query_graph',
  'get_architecture',
  'search_code',
];

/** pi tool name -> normalized action the policy understands. */
const ACTION_BY_TOOL = {
  read: 'read',
  write: 'write',
  edit: 'write',
  bash: 'bash',
};

const isSignalTool = (name) =>
  SIGNAL_TOOLS.some((s) => name === s || name.endsWith(`_${s}`));

const fallback = (why) => ({
  policy: {
    name: 'enforce-rules',
    version: 1,
    description: 'built-in fallback because the policy could not be read',
    reminded: '',
    checks: [],
    config: { max_blocks_per_session: 0, signal_ttl_ms: 0 },
  },
  error: why,
});

/** Append text to a pi message content, which is either a string or blocks. */
const appendText = (content, text) => {
  if (typeof content === 'string') return `${content}\n\n${text}`;
  if (Array.isArray(content)) return [...content, { type: 'text', text }];
  return content; // unknown shape: leave it alone rather than corrupt it
};

export default function enforceRules(pi, options = {}) {
  const resolved = firstExistingPolicy(HERE, options.policyPath ?? null);
  const loaded = options.policy
    ? policyFromObject(options.policy)
    : resolved
      ? loadPolicy(resolved)
      : {
          ok: false,
          error:
            `no policy file found; looked in:\n` +
            policyCandidates(HERE, options.policyPath ?? null)
              .map((c) => `    ${c}`)
              .join('\n'),
        };
  const { policy, error } = loaded.ok
    ? loaded
    : fallback(`policy not loaded (${loaded.error})`);

  const state = newSessionState();
  /** Set once per session so the same advisory is not repeated. */
  let noticedPolicyProblem = false;
  /**
   * The directory pi resolves a relative tool path against.
   *
   * pi's `read` schema accepts "relative or absolute" and resolves the relative
   * form against the session directory, so a rule that only understands
   * absolute paths would be dodged by spelling the same file relatively. The
   * value is captured at session start and refreshed from `ctx` on every call,
   * because `ctx.cwd` is not guaranteed on every event.
   *
   * Left null when nothing has ever supplied one: guessing here would scope a
   * read into whatever directory the pi process happened to start in, which is
   * a different repository. Without a cwd the path stays relative, the policy
   * refuses it, and the gate is inert — the same behaviour as before this was
   * fixed, and the honest floor.
   */
  let sessionCwd = null;
  const cwdFor = (ctx) =>
    typeof ctx?.cwd === 'string' && ctx.cwd ? ctx.cwd : sessionCwd;

  pi.on('session_start', async (_event, ctx) => {
    state.blocks = 0;
    state.signals = 0;
    state.written.clear();
    if (typeof ctx?.cwd === 'string' && ctx.cwd) sessionCwd = ctx.cwd;
    if (error) {
      // A gate that cannot load its policy is OFF. Say so loudly: in a headless
      // run there is no UI to notify, so this also goes to stderr. A silent
      // no-op enforcement point is worse than no enforcement point at all,
      // because everyone believes the rules are being enforced.
      process.stderr.write(`[enforce-rules] DISABLED: ${error}\n`);
      if (ctx?.hasUI && !noticedPolicyProblem) {
        noticedPolicyProblem = true;
        ctx.ui.notify(`enforce-rules: ${error}; gate is inactive`, 'warn');
      }
      return;
    }
    if (ctx?.hasUI) {
      ctx.ui.notify(
        `enforce-rules: ${policy.name} active (${policy.checks.join(', ') || 'no checks'})`,
        'info',
      );
    }
  });

  pi.on('tool_call', async (event, ctx) => {
    const name = event.toolName;
    const cwd = cwdFor(ctx);

    // Remember what this session wrote: reading your own output is never a
    // violation, and blocking it would make the gate fight normal development.
    // The path is normalized on BOTH sides (here and in the read branch below),
    // so a file written as "src/a.ts" and read back as an absolute path — or
    // spelled with a different drive case on Windows — is still recognized as
    // the model's own file.
    if (name === 'write' || name === 'edit') {
      const path = normalizePath(event.input?.path ?? null, cwd);
      recordWrite(state, path);
      const content = typeof event.input?.content === 'string' ? event.input.content : null;
      const verdict = shouldBlock({
        policy,
        input: { action: 'write', path, tool: name, content },
        state,
        fs: realFs,
      });
      if (verdict.block) {
        return { block: true, reason: verdict.reason };
      }
      return;
    }

    if (name !== 'read') return;

    const verdict = shouldBlock({
      policy,
      input: { action: 'read', path: normalizePath(event.input?.path ?? null, cwd), tool: name },
      state,
      fs: realFs,
    });

    if (verdict.block) {
      if (ctx?.hasUI) {
        ctx.ui.notify(
          `enforce-rules [${verdict.code}] block ${state.blocks}/${policy.config.max_blocks_per_session}`,
          'warn',
        );
      }
      return { block: true, reason: verdict.reason };
    }

    if (verdict.capReached && ctx?.hasUI && !noticedPolicyProblem) {
      noticedPolicyProblem = true;
      ctx.ui.notify(
        'enforce-rules: block cap reached, the gate is now inactive for this session',
        'warn',
      );
    }
    return;
  });

  pi.on('tool_result', async (event) => {
    if (event.isError) return;
    // Only a *successful* graph query unlocks the session. A failed query means
    // the model has not actually learned anything yet.
    if (isSignalTool(event.toolName)) {
      recordSignal(state);
      return;
    }
    // pi-mcp-adapter's default proxy mode reports every MCP call as the single
    // `mcp` tool and names the real tool in the input. Count a successful proxy
    // call to a graph tool as a query too: without this the gate could never
    // open on a host whose MCP tools are proxy-only, and it would silently
    // degrade to "block three reads, then stop enforcing".
    if (event.toolName === 'mcp' && isSignalTool(String(event.input?.tool ?? ''))) {
      recordSignal(state);
    }
  });

  pi.on('context', async (event) => {
    const reminder = reminderFor(policy, state);
    if (!reminder) return;
    const messages = event.messages;
    if (!Array.isArray(messages) || messages.length === 0) return;

    const last = messages[messages.length - 1];
    if (last?.role === 'user') {
      messages[messages.length - 1] = {
        ...last,
        content: appendText(last.content, reminder),
      };
    } else {
      messages.push({ role: 'user', content: reminder });
    }
    return { messages };
  });
}
